# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c082696968cf38679e3e481b26b28f9795a662f4f17fbc32b278259c9eceb8b6a3f632f63b2cb9234b843d3c70c5841343a5bc34939e94dd5667c7c29f665a6b

test:
  secret_key_base: 71a55b4bf98aac28c9df96bca3e1726a1523c13e96c91ff5d19e0ad2acff8df69ba4d64988d8ec53fd4231920176ed6e702bfde4ca3fc111463fb0f308e2ea08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
